[package]
name = "rust-echo-server"
version = "0.1.0"
authors = ["Mark S. Everitt <mark.s.everitt@gmail.com>"]

[dependencies]
hyper = "0.12"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
